export default  {
    START_API:'START_API',
    LOGIN : 'LOGIN',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILED : 'LOGIN_FAILED',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    LOGOUT:'LOGOUT'
};
